name: py-ds-prj

services:
  py-ds:
    image: py-ds-img
    build:
      context: .
      dockerfile: Dockerfile

    container_name: py-ds-cont

    ports:
      - "8888:8888"
      - "8889:8889"
      - "8890:8890"
      - "8891:8891"
      - "8892:8892"
    
    volumes:
      - ./:/usr/src/app # mount the current directory to /usr/src/app

    extra_hosts:
      - "host.docker.internal:host-gateway"
    
    command: /usr/src/app/start-kernel.sh

networks:
  default:
    name: py-ds-net