name: py-ds-prj

services:
  py-ds:
    image: py-ds-img
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: "normal"
        INST_EXTRA: "false"
        EXTRA_PACKS: "requirements/requirements_opt.txt"

    container_name: py-ds-cont

    ports:
      - "8888:8888"
      - "8889:8889"
      - "8890:8890"
      - "8891:8891"
      - "8892:8892"
    
    volumes:
      - ./data:/data # mount the current data directory to /app/data in the container

    extra_hosts:
      - "host.docker.internal:host-gateway"
    
    command: /app/start-kernel.sh

networks:
  default:
    name: py-ds-net