name: py-ds-prj

services:
  py-ds-srv:
    image: py-ds
    tags:
      - py-ds:latest
      - py-ds:1.0-normal # remember to change it, if you change args
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: "normal"
        INST_EXTRA: "false"
        EXTRA_PACKS: "requirements_opt.txt"

    container_name: py-ds-cont

    ports:
      - "8888:8888"
      - "8889:8889"
      - "8890:8890"
      - "8891:8891"
      - "8892:8892"
    
    volumes:
      - ./data:/app/data # mount the current data directory to /app/data in the container

    extra_hosts:
      - "host.docker.internal:host-gateway"
    
    command: ./start-kernel.sh

networks:
  default:
    name: py-ds-net