name: py-ds-prj

services:
  py-ds-srv:
    image: py-ds-dev:latest

    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: "normal"
        INST_EXTRA: "false"
        EXTRA_PACKS: "requirements_opt.txt"

    container_name: py-ds-cont

    ports:
      - "8888:8888"
      - "8889:8889"
      - "8890:8890"
      - "8891:8891"
      - "8892:8892"

    environment:
      - WORK_DIR=/workspace
      - CURR_USR=pyuser
    
    user: pyuser  # non-root user
    
    volumes:
      - ./data:/workspace/data # mount the current data directory to WORKDIR in the container
      - ./kernel:/workspace/kernel # mount the current kernel directory to WORKDIR in the container

    extra_hosts:
      - "host.docker.internal:host-gateway"
    
    command: ./start-kernel.sh

networks:
  default:
    name: py-ds-net